
import numpy as np
from hypothesis import given, strategies as st, settings, HealthCheck, Verbosity
from e8leech.lattices.e8_lattice import E8Lattice

# Initialize E8 lattice once for all tests
e8_lattice = E8Lattice()

@settings(deadline=None, suppress_health_check=[HealthCheck.filter_too_much, HealthCheck.too_slow])
@given(st.lists(st.integers(min_value=-5, max_value=5), min_size=8, max_size=8))
def test_e8_root_vector_norm(coords):
    """
    Test that E8 root vectors have a squared norm of 2.
    This test focuses on the property of the E8 root system.
    """
    # The E8Lattice class generates its own root system. We\'ll test those.
    roots = e8_lattice.generate_root_system()
    
    # Check a sample of roots, or all if the list is small
    sample_size = min(len(roots), 100) # Limit for performance
    for i in range(sample_size):
        root = roots[i]
        squared_norm = np.dot(root, root)
        assert np.isclose(squared_norm, 2.0), f"Root {root} has squared norm {squared_norm}, expected 2.0"

@settings(deadline=None, suppress_health_check=[HealthCheck.filter_too_much, HealthCheck.too_slow])
@given(st.lists(st.floats(min_value=-10.0, max_value=10.0, allow_nan=False, allow_infinity=False), min_size=8, max_size=8))
def test_babai_nearest_plane_output_is_lattice_point(target_point):
    """
    Test that Babai\'s nearest plane algorithm returns a valid lattice point.
    """
    nearest_point = e8_lattice.nearest_neighbor(np.array(target_point), algorithm="babai")
    
    # A point x is in E8 if x is in Z^8 or x is in (Z+1/2)^8 and sum of coordinates is even
    # For E8, all coordinates are either integers or half-integers.
    # And the sum of coordinates must be an even integer.
    
    # Check if all coordinates are integers or half-integers
    is_integer_or_half_integer = np.all(np.isclose(nearest_point * 2, np.round(nearest_point * 2)))
    assert is_integer_or_half_integer, f"Point {nearest_point} is not integer or half-integer"
    
    # Check if sum of coordinates is an even integer
    sum_coords = np.sum(nearest_point)
    assert np.isclose(sum_coords % 2, 0.0) or np.isclose(sum_coords % 2, 2.0), f"Sum of coords {sum_coords} is not even integer"

@settings(deadline=None, suppress_health_check=[HealthCheck.filter_too_much, HealthCheck.too_slow])
@given(st.lists(st.integers(min_value=-5, max_value=5), min_size=8, max_size=8))
def test_e8_even_lattice_property(coords):
    """
    Test that the E8 lattice is an even lattice (all squared norms are even integers).
    This tests the property on points generated by integer linear combinations of the basis.
    """
    # Generate a lattice point using the E8 basis
    coeffs = np.array(coords)
    lattice_point = np.dot(coeffs, e8_lattice.basis)
    
    squared_norm = np.dot(lattice_point, lattice_point)
    
    # Due to floating point precision, check if it\'s close to an even integer
    assert np.isclose(squared_norm % 2, 0.0) or np.isclose(squared_norm % 2, 2.0), f"Squared norm {squared_norm} is not an even integer"

@settings(deadline=None, suppress_health_check=[HealthCheck.filter_too_much, HealthCheck.too_slow])
@given(st.lists(st.floats(min_value=-10.0, max_value=10.0, allow_nan=False, allow_infinity=False), min_size=8, max_size=8))
def test_lattice_quantization_output_is_lattice_point(target_point):
    """
    Test that lattice quantization returns a valid E8 lattice point.
    """
    quantized_point = e8_lattice.quantize(np.array(target_point), algorithm="babai")
    
    # Check if all coordinates are integers or half-integers
    is_integer_or_half_integer = np.all(np.isclose(quantized_point * 2, np.round(quantized_point * 2)))
    assert is_integer_or_half_integer, f"Quantized point {quantized_point} is not integer or half-integer"
    
    # Check if sum of coordinates is an even integer
    sum_coords = np.sum(quantized_point)
    assert np.isclose(sum_coords % 2, 0.0) or np.isclose(sum_coords % 2, 2.0), f"Sum of coords {sum_coords} is not even integer"



