
import numpy as np
from hypothesis import given, strategies as st, settings, HealthCheck
from e8leech.lattices.leech_lattice import LeechLattice
from e8leech.lattices.e8_lattice import E8Lattice

# Initialize Leech lattice once for all tests
leech_lattice = LeechLattice()
e8_lattice_for_congruence = E8Lattice() # For congruence condition checks

@settings(deadline=None, suppress_health_check=[HealthCheck.filter_too_much, HealthCheck.too_slow])
@given(st.lists(st.integers(min_value=-5, max_value=5), min_size=24, max_size=24))
def test_leech_unimodularity(coords):
    """
    Test that the Leech lattice is unimodular (determinant of Gram matrix is 1).
    This checks the basis construction.
    """
    # The unimodularity is a property of the basis itself.
    # We check the determinant of the Gram matrix of the Leech lattice basis.
    determinant = leech_lattice.determinant
    assert np.isclose(determinant, 1.0), f"Leech lattice determinant is {determinant}, expected 1.0"

@settings(deadline=None, suppress_health_check=[HealthCheck.filter_too_much, HealthCheck.too_slow])
@given(st.lists(st.integers(min_value=-5, max_value=5), min_size=24, max_size=24))
def test_leech_even_lattice_property(coords):
    """
    Test that the Leech lattice is an even lattice (all squared norms are even integers).
    This tests the property on points generated by integer linear combinations of the basis.
    """
    # Generate a lattice point using the Leech basis
    coeffs = np.array(coords)
    lattice_point = np.dot(coeffs, leech_lattice.basis)
    
    squared_norm = np.dot(lattice_point, lattice_point)
    
    # Due to floating point precision, check if it\"s close to an even integer
    assert np.isclose(squared_norm % 2, 0.0) or np.isclose(squared_norm % 2, 2.0), f"Squared norm {squared_norm} is not an even integer"

@settings(deadline=None, suppress_health_check=[HealthCheck.filter_too_much, HealthCheck.too_slow])
@given(st.lists(st.floats(min_value=-10.0, max_value=10.0, allow_nan=False, allow_infinity=False), min_size=24, max_size=24))
def test_leech_quantization_output_is_lattice_point(target_point):
    """
    Test that lattice quantization returns a valid Leech lattice point.
    """
    quantized_point = leech_lattice.quantize(np.array(target_point), algorithm="babai")
    
    # For Leech lattice, all coordinates are integers or half-integers.
    # And the sum of coordinates must be an even integer.
    
    # Check if all coordinates are integers or half-integers
    is_integer_or_half_integer = np.all(np.isclose(quantized_point * 2, np.round(quantized_point * 2)))
    assert is_integer_or_half_integer, f"Quantized point {quantized_point} is not integer or half-integer"
    
    # Check if sum of coordinates is an even integer
    sum_coords = np.sum(quantized_point)
    assert np.isclose(sum_coords % 2, 0.0) or np.isclose(sum_coords % 2, 2.0), f"Sum of coords {sum_coords} is not even integer"

# Note: Testing the congruence conditions (x ≡ y ≡ z mod 2E8 and x+y+z ≡ 0 mod 4E8)
# is more complex as it requires generating specific points that are known to be in the Leech lattice
# and then decomposing them into E8 components. This might be better suited for example-based tests
# or more advanced property-based strategies that can generate such structured inputs.
# For now, we will focus on the fundamental properties of the lattice itself.



